TARGET := gdev

src_drv := gdev_drv.o gdev_drv_nvidia.o gdev_fops.o gdev_ioctl.o gdev_proc.o
src_common := gdev_api.o gdev_device.o gdev_nvidia.o gdev_nvidia_compute.o gdev_nvidia_fifo.o gdev_nvidia_mem.o gdev_nvidia_nv50.o gdev_nvidia_nvc0.o gdev_nvidia_nve4.o


ifneq ($(KERNELRELEASE),)
#$(TARGET)-objs := gdev_drv.o gdev_drv_nvidia.o gdev_fops.o gdev_ioctl.o gdev_proc.o
#$(TARGET)-objs += gdev_api.o gdev_device.o gdev_sched.o
$(TARGET)-objs += $(files)

files += $(foreach f,$(src_drv), $(CURDIR)/$(f))
files += $(foreach f,$(src_common), $(CURDIR)/../../common/$(f))

obj-m := $(TARGET).o
EXTRA_CFLAGS +=-I$(PWD)/../../common -I$(PWD) -I$(PWD)/../../util

else
ifndef LINUX_DIR
LINUX_DIR	:= /lib/modules/$(shell uname -r)/build
endif
PWD	:= $(shell pwd)
include $(PWD)/Driver.mk # export $(DRIVER_NAME)

endif


SYSSRC = $(LINUX_DIR)

GDEVDIR = /usr/local/gdev
GDEVINC = $(GDEVDIR)/include
GDEVETC = $(GDEVDIR)/etc

EXTRA_CFLAGS += -Iinclude/drm  -DGDEV_SCHED_DISABLED

all:
	$(MAKE)	-C $(SYSSRC) M=$(PWD) ENABLE_WARN_DEPRECATED=1 modules

clean:
	$(MAKE) -C $(SYSSRC) M=$(PWD) clean
	rm -f *~

install: all
	-sudo rmmod $(TARGET)
	+sudo make -C $(SYSSRC) M=$(PWD) modules_install
	sudo install -o root -m 0755 -d $(GDEVDIR)
	sudo install -o root -m 0755 -d $(GDEVINC)
	sudo install -o root -m 0755 -d $(GDEVETC)
	sudo install -o root -m 0644 Module.symvers \
	             $(GDEVETC)/Module.symvers.$(TARGET)
	sudo install -o root -m 0644 gdev_api.h gdev_autogen.h \
	             gdev_nvidia_def.h gdev_list.h gdev_time.h $(GDEVINC)
	sudo install -o root -m 0644 $(TARGET).rules \
	             /etc/udev/rules.d/80-$(TARGET).rules
	-sudo modprobe $(TARGET)

uninstall:
	-sudo rmmod $(TARGET)
	sudo rm -f $(GDEVETC)/Module.symvers.$(TARGET)
	sudo rm -f $(GDEVINC)/gdev_api.h $(GDEVINC)/gdev_autogen.h \
	        $(GDEVINC)/gdev_nvidia_def.h $(GDEVINC)/gdev_list.h \
	        $(GDEVINC)/gdev_time.h
	sudo rm -f /lib/modules/$(shell uname -r)/extra/$(TARGET).ko
	sudo depmod
