# Makefile
TARGET	= user_test
CC=aarch64-none-linux-gnu-gcc
NVCC	+= nvcc -arch sm_20 -cubin
LIBS	+= -lucuda -lgdev
CFLAGS	+= -L/home/b/2.5bay/mthesis-unsync/projects/trusted-periph/buildconf/gdev/install/gdev/lib/lib64/ -I/home/b/2.5bay/mthesis-unsync/projects/trusted-periph/buildconf/gdev/install/gdev/include/

nvcc:
	$(NVCC) -ccbin /usr/local/cuda/bin -o madd_gpu.cubin madd_gpu.cu
gcc:
	$(CC) -o $(TARGET) $(CFLAGS) main.c madd.c $(LIBS)
clean:
	rm -f $(TARGET) *.cubin ./*~
