# Makefile
TARGET	= user_test
CC=aarch64-none-linux-gnu-gcc
NVCC	+= nvcc -arch sm_20 -cubin
LIBS	+= -L/home/armcca/trusted-peripherals/assets/snapshots/aarch64-lib -lucuda -lgdev
CFLAGS	+= -I/usr/local/gdev/include

nvcc:
	$(NVCC) -ccbin /usr/local/cuda/bin -o madd_gpu.cubin madd_gpu.cu
gcc:
	$(CC) -o $(TARGET) $(CFLAGS) main.c madd.c $(LIBS)
clean:
	rm -f $(TARGET) *.cubin ./*~
